const fs=require('fs');const assert=require('assert');
const index=fs.readFileSync('frontend/index.html','utf8');
const app=fs.readFileSync('frontend/beta-mobile.html','utf8');
const legal=fs.readFileSync('frontend/legal-center.html','utf8');
assert(index.includes('id="acciones"'));
['Enviar y','Solicitar','Compraventa','Operaciones<br>condicionadas','Conciliación<br>inteligente','legal-center.html'].forEach(x=>assert(index.includes(x),x));
assert(index.includes('SOLUCIONES EN UNA ÚNICA APP'));
assert(index.includes('beta-mobile.html'));
['data-view="operations"','data-view="logistics"','data-view="evidence"','data-view="identity"','data-view="wallet"','data-view="premium"','data-view="dashboard"','legal-center.html','Marco jurídico'].forEach(x=>assert(app.includes(x),x));
assert(app.includes('SIN DINERO REAL')&&app.includes('NO_PII')&&app.includes('SHADOW / READ-ONLY'));
['Derechos e intereses legítimos de FIA&CO','Obligaciones cuando resulten aplicables','Gate fotográfico antes de habilitar el pago','Derechos y obligaciones correlativas','Fuentes oficiales'].forEach(x=>assert(legal.includes(x),x));
assert(legal.includes('www.boe.es')&&legal.includes('eur-lex.europa.eu')&&legal.includes('poderjudicial.es'));
assert(/no convierte a FIA&CO en perito, transportista, asegurador ni garante/i.test(legal));
assert(/validación jurídica|validación profesional/i.test(legal));
console.log('unified action index and legal center tests passed');
