const assert=require('assert');
const fs=require('fs');
const path=require('path');
require('../frontend/js/growth-strategy.js');
require('../frontend/js/capital-readiness.js');
const growth=globalThis.FIACOGrowthStrategy;
const kit=globalThis.FIACOCapitalReadiness;
const consolidated=growth.evaluate({metrics:{dataSource:'OBSERVED',legalCommercialReady:true,observedRevenueMonths:6,activeBusinesses:20,retentionPct:75,monthlyOperatingResult:1500,cashCoverageMonths:5,growthDemandPct:30}});
assert.strictEqual(consolidated.state,'PREPARE_GROWTH_FINANCING');
const incomplete=kit.evaluate(consolidated,{productBudget:10000,commercialBudget:5000,securityComplianceBudget:3000,operationsBudget:2000,contingencyPct:10});
assert.strictEqual(incomplete.status,'PREPARE_MATERIALS');
assert.strictEqual(incomplete.investorOutreachAllowed,false);
assert.strictEqual(incomplete.externalContactRequiresFounderApproval,true);
assert.deepStrictEqual(incomplete.capitalPreparationOwners,['FOUNDER','AI_ASSIST']);
const ready=kit.evaluate(consolidated,{observedMetricsReady:true,financialModelReady:true,legalPackReady:true,dataRoomReady:true,milestonePlanReady:true,securityPackReady:true,productBudget:10000,commercialBudget:5000,securityComplianceBudget:3000,operationsBudget:2000,contingencyPct:10});
assert.strictEqual(ready.status,'READY_FOR_JOINT_CAPITAL_RESEARCH');
assert.strictEqual(ready.readinessPct,100);
assert.strictEqual(ready.milestoneSubtotal,20000);
assert.strictEqual(ready.plannedCapitalNeed,22000);
assert.strictEqual(ready.termAcceptanceAllowed,false);
assert.strictEqual(ready.debtAcceptanceAllowed,false);
assert.strictEqual(ready.dilutionAcceptanceAllowed,false);
assert.strictEqual(ready.autonomousCapitalCommitment,false);
const early=growth.evaluate({metrics:{dataSource:'DEMO',legalCommercialReady:false,observedRevenueMonths:0,activeBusinesses:0,retentionPct:0,monthlyOperatingResult:0,cashCoverageMonths:0,growthDemandPct:90}});
const wait=kit.evaluate(early,{observedMetricsReady:true,financialModelReady:true,legalPackReady:true,dataRoomReady:true,milestonePlanReady:true,securityPackReady:true});
assert.strictEqual(wait.status,'WAIT_FOR_CONSOLIDATION');
assert.strictEqual(wait.investorResearchAllowed,false);
const capped=kit.evaluate(consolidated,{contingencyPct:99,productBudget:-10});
assert.strictEqual(capped.contingencyPct,30);
assert.strictEqual(capped.budget.product,0);
const html=fs.readFileSync(path.join(__dirname,'../frontend/capital-readiness-kit.html'),'utf8');
assert(html.includes('FOUNDER + AI_ASSIST'));
assert(html.includes('NO OUTREACH AUTOMÁTICO'));
assert(!html.includes('localStorage'));
assert(!html.includes('https://'));
console.log('capital readiness tests passed');
