import fs from 'node:fs';
import assert from 'node:assert/strict';
import { runSyntheticOperationLifecycle } from '../core/pilot/synthetic-operation-lifecycle.mjs';
import { buildSyntheticAssuranceReport } from '../core/pilot/synthetic-assurance-report.mjs';
import { runSyntheticAdversarialCampaign,summarizeAdversarialCampaign } from '../core/pilot/synthetic-adversarial-campaign.mjs';
import { runSyntheticOperationalResilience } from '../core/pilot/synthetic-operational-resilience.mjs';
import { evaluateSyntheticFraudDispute,summarizeSyntheticFraudDisputes } from '../core/pilot/synthetic-fraud-dispute.mjs';
import { buildConsolidatedSimulationReport } from '../core/pilot/consolidated-simulation-report.mjs';
const read=path=>JSON.parse(fs.readFileSync(path,'utf8'));

const operationAssurance=buildSyntheticAssuranceReport(read('config/synthetic-operation-lifecycle.v1.json').cases.map(runSyntheticOperationLifecycle));
const campaigns=[];for(const item of read('config/synthetic-adversarial-campaign.v1.json').campaigns)campaigns.push(await runSyntheticAdversarialCampaign({...item,syntheticOnly:true}));
const adversarial=summarizeAdversarialCampaign(campaigns);
const resilience=await runSyntheticOperationalResilience(read('config/synthetic-resilience-campaign.v1.json'));
const disputes=summarizeSyntheticFraudDisputes(read('config/synthetic-fraud-dispute-cases.v1.json').cases.map(item=>evaluateSyntheticFraudDispute({...item,synthetic:true})));
const report=buildConsolidatedSimulationReport({operationAssurance,adversarial,resilience,disputes});
assert.equal(report.decision,'PASS_SIMULATION_PROGRAM');
assert.equal(report.domainsChecked,4);
assert.equal(report.domainsPassed,4);
assert.equal(report.statistics.completeOperationLifecycles,3);
assert.equal(report.statistics.standardFailureDrills,10);
assert.equal(report.statistics.adversarialCampaigns,3);
assert.equal(report.statistics.combinedFaults,8);
assert.equal(report.statistics.failedRecoveryAttempts,3);
assert.equal(report.statistics.fraudDisputeCases,12);
assert.equal(report.statistics.humanDisputeReviews,7);
assert.equal(report.statistics.blockedOrFrozenDisputes,11);
assert.equal(report.statistics.boundaryViolations,0);
assert.equal(report.productionReady,false);
const blocked=buildConsolidatedSimulationReport({operationAssurance:{...operationAssurance,decision:'BLOCK_REGRESSION',boundaryViolations:1},adversarial,resilience,disputes});
assert.equal(blocked.decision,'BLOCK_SIMULATION_PROGRAM');
assert.ok(blocked.failedDomains.includes('operationLifecycle'));
assert.ok(blocked.failedDomains.includes('securityBoundaries'));
console.log('consolidated-simulation-report: ok');
