import fs from 'node:fs';
import assert from 'node:assert/strict';
import {runControlledPrepilot} from '../core/pilot/controlled-prepilot.mjs';
const config=JSON.parse(fs.readFileSync('config/controlled-prepilot.v1.json','utf8'));
const report=runControlledPrepilot(config);
assert.equal(report.syntheticGateDecision,'PASS_SYNTHETIC_PREPILOT_GATE');
assert.equal(report.realUserDecision,'NOT_READY_FOR_CONTROLLED_PREPILOT');
assert.equal(report.lifecycle.users,2);
assert.equal(report.lifecycle.stagesCompleted,5);
assert.equal(report.access.passed,true);
assert.equal(report.access.checks.length,3);
assert.equal(report.retention.passed,true);
assert.equal(report.retention.deletedValues,3);
assert.equal(report.security.passed,true);
assert.equal(report.security.scenarios,4);
assert.equal(report.dispute.humanReviewRequired,true);
assert.equal(report.dispute.automaticWinnerSelected,false);
assert.equal(report.dispute.financialInstructionCreated,false);
assert.equal(report.blockers.length,6);
assert.equal(report.requirements.filter(x=>x.category==='DEFERRABLE').length,2);
assert.equal(report.productionReady,false);
assert.equal(report.realDataUsed,false);
assert.equal(report.realMoneyMoved,false);
assert.throws(()=>runControlledPrepilot({...config,syntheticOnly:false}),/SYNTHETIC_ONLY/);
assert.throws(()=>runControlledPrepilot({...config,operation:{...config.operation,realMoney:true}}),/FINANCIAL_BOUNDARY/);
console.log('controlled-prepilot: ok');
