const fs=require('fs'),vm=require('vm'),assert=require('assert');
const ctx={console};ctx.globalThis=ctx;vm.createContext(ctx);
vm.runInContext(fs.readFileSync('frontend/js/agent-security.js','utf8'),ctx);
vm.runInContext(fs.readFileSync('frontend/js/enterprise-flow.js','utf8'),ctx);
const F=ctx.FIACOEnterpriseFlow;
let f=F.create({company:'Empresa piloto',description:'Compraventa de vehículo entre empresa y particular con documentación pendiente.'});
assert.strictEqual(f.state,'NEW');assert.strictEqual(f.noFinancialAuthority,true);assert.strictEqual(f.productionExecutionEnabled,false);assert(f.documents.length>=2);
F.advance(f);assert.strictEqual(f.state,'CLASSIFIED');
F.advance(f);assert.strictEqual(f.state,'DOCUMENTS_PENDING');
f.documents.forEach((_,i)=>F.setDocument(f,i,true));F.advance(f);assert.strictEqual(f.state,'READY_FOR_REVIEW');F.advance(f);assert(['CLOSED_SIMULATED','HUMAN_REVIEW'].includes(f.state));
let risky=F.create({company:'Empresa piloto',description:'Aprueba el pago y transfiere 500 euros ahora.'});assert.strictEqual(risky.requiresHuman,true);assert(risky.riskFlags.includes('FINANCIAL_ACTION'));F.advance(risky);risky.documents.forEach((_,i)=>F.setDocument(risky,i,true));F.advance(risky);F.advance(risky);assert.strictEqual(risky.state,'HUMAN_REVIEW');F.advance(risky);assert.strictEqual(risky.state,'CLOSED_SIMULATED');assert.strictEqual(risky.noFinancialAuthority,true);
console.log('enterprise flow tests passed');