const assert=require('assert');
require('../frontend/js/agent-security.js');
require('../frontend/js/enterprise-flow.js');
require('../frontend/js/enterprise-ops-dashboard.js');
const d=globalThis.FIACOEnterpriseOpsDashboard;
let flow=globalThis.FIACOEnterpriseFlow.create({company:'Empresa Demo',description:'Compraventa de vehículo con documentación pendiente'});
flow=globalThis.FIACOEnterpriseFlow.advance(flow);
const item=d.fromFlow(flow,{alias:'Caso A',segment:'TRANSPORT',amount:8000,createdAt:1700000000000});
assert.strictEqual(item.containsPersonalData,false);
assert.strictEqual(item.persistentStorage,false);
assert.strictEqual(item.productionExecutionEnabled,false);
assert.strictEqual(item.noFinancialAuthority,true);
assert(!('company' in item));
assert(!('description' in item));
const summary=d.summarize([item],'ALL',1700000000000);
assert.strictEqual(summary.count,1);
assert.strictEqual(summary.amount,8000);
assert.strictEqual(summary.containsPersonalData,false);
assert.strictEqual(summary.noFinancialAuthority,true);
const old=d.fromFlow(flow,{alias:'Old',segment:'OTHER',amount:100,createdAt:1600000000000});
assert.strictEqual(d.summarize([item,old],'7D',1700000000000).count,1);
const risky=Object.assign({},item,{id:'X',riskCount:2,requiresHuman:true,pendingDocuments:1});
assert.strictEqual(d.priorities([item,risky])[0].id,'X');
assert.throws(()=>d.summarize([item],'BAD',1700000000000),/Periodo no válido/);
console.log('enterprise ops dashboard tests passed');
