const assert=require('assert');
require('../frontend/js/founder-hiring-kit.js');
const k=globalThis.FIACOFounderHiringKit;
const kit=k.build('OPS_ASSISTANT',{operations:120,humanMinutesPerOperation:12,hiringSignal:'PREPARE_HIRE'});
assert.strictEqual(kit.decisionOwner,'FOUNDER');
assert.strictEqual(kit.interviewOwner,'FOUNDER');
assert.strictEqual(kit.offerOwner,'FOUNDER');
assert.strictEqual(kit.candidateRankingAllowed,false);
assert.strictEqual(kit.automatedCandidateDecision,false);
assert.strictEqual(kit.autoInterviewAllowed,false);
assert.strictEqual(kit.autoOfferAllowed,false);
assert.strictEqual(kit.noHiringAction,true);
assert.strictEqual(kit.noFinancialCommitment,true);
assert.strictEqual(kit.persistentStorage,false);
assert.strictEqual(kit.containsCandidatePersonalData,false);
assert(kit.scorecard.length>=4);
assert(kit.scorecard.every(x=>x.owner==='FOUNDER'));
assert(kit.interviewQuestions.length>=5);
console.log('founder hiring kit tests passed');
