const fs=require('fs'),assert=require('assert');
const web=fs.readFileSync('frontend/web-beta.html','utf8');
const app=fs.readFileSync('frontend/beta-mobile.html','utf8');
const unified=fs.readFileSync('frontend/js/unified-app.js','utf8');
const css=fs.readFileSync('frontend/css/fia-home-final.css','utf8');
const art=fs.readFileSync('frontend/assets/office-fia-hero.svg','utf8');
['Conecta.','Acuerda.','Gestiona.','Comprueba.','Compraventa','Venta + transporte','Porte especial','Transporte animal','Proveedores','Transportistas','Empresas','Colaboradores','Premium','Marco jurídico','Panel operativo'].forEach(x=>assert(web.includes(x),`web ${x}`));
['Todo FIA&CO, junto.','Operaciones','Logística','Evidencias','Identidad','Cartera demo','Premium','Marco jurídico','Dashboard','Porte especial'].forEach(x=>assert(app.includes(x),`app ${x}`));
assert(unified.includes('Transporte animal'),'app Transporte animal');
assert(unified.includes("'animal'")&&unified.includes('needsLogistics'),'animal transport must use the coordinated logistics path');
assert(web.includes('FIA&CO coordina digitalmente; terceros ejecutan servicios físicos'));
assert(app.includes('El transporte físico corresponde siempre a terceros habilitados'));
assert(app.includes('SIN DINERO REAL')&&app.includes('NO_PII')&&app.includes('SHADOW / READ-ONLY'));
assert(css.includes('@media(prefers-reduced-motion:reduce)'));
assert(css.includes('fiaAmp'));
assert(art.includes('FIA&amp;CO') || art.includes('FIA'));
assert(!web.includes('+5.000') && !web.includes('+1.200') && !web.includes('+850'));
console.log('Full web/mobile beta visual gate passed');
