const assert=require('assert');
require('../frontend/js/growth-strategy.js');
const g=globalThis.FIACOGrowthStrategy;
let r=g.evaluate({metrics:{dataSource:'DEMO'}});
assert.strictEqual(r.state,'STAY_FOUNDER_LED');
assert.strictEqual(r.consolidated,false);
assert.strictEqual(r.noFinancialCommitment,true);
assert.strictEqual(r.noExternalOutreach,true);
let h=g.evaluate({capacity:{hiringSignal:'PREPARE_HIRE'},hireGate:{recommendation:'FOUNDER_REVIEW'},metrics:{dataSource:'DEMO'}});
assert.strictEqual(h.state,'FOUNDER_REVIEW_FOR_HIRE');
let c=g.evaluate({metrics:{dataSource:'OBSERVED',observedRevenueMonths:4,activeBusinesses:15,retentionPct:75,monthlyOperatingResult:1800,cashCoverageMonths:7,growthDemandPct:30,legalCommercialReady:true}});
assert.strictEqual(c.consolidated,true);
assert.strictEqual(c.state,'PREPARE_GROWTH_FINANCING');
assert.deepStrictEqual(c.capitalPreparationOwners,['FOUNDER','AI_ASSIST']);
assert.strictEqual(c.investorOutreachRequiresFounderApproval,true);
assert.strictEqual(c.autonomousCapitalCommitment,false);
let n=g.evaluate({metrics:{dataSource:'OBSERVED',observedRevenueMonths:4,activeBusinesses:15,retentionPct:75,monthlyOperatingResult:1800,cashCoverageMonths:7,growthDemandPct:5,legalCommercialReady:true}});
assert.strictEqual(n.consolidated,true);
assert.strictEqual(n.state,'STAY_FOUNDER_LED');
console.log('growth strategy tests passed');
