const assert=require('assert');
const fs=require('fs');
const path=require('path');
require('../frontend/js/hire-runway-gate.js');
const g=globalThis.FIACOHireRunwayGate;
const profile={economicallyReady:true,monthlyCost:900,monthlyNetImpact:300};
const ready=g.evaluate(profile,{currentCash:10000,existingMonthlyCashExpenses:600,currentMonthlyOperatingResult:1200,positiveMonths:3,requiredPositiveMonths:3,reserveMonths:6});
assert.strictEqual(ready.recommendation,'FOUNDER_REVIEW');
assert.strictEqual(ready.readyForFounderReview,true);
assert.strictEqual(ready.readyForManualReview,true);
assert.strictEqual(ready.decisionOwner,'FOUNDER');
assert.strictEqual(ready.interviewOwner,'FOUNDER');
assert.strictEqual(ready.offerOwner,'FOUNDER');
assert.strictEqual(ready.candidateRankingAllowed,false);
assert.strictEqual(ready.automatedCandidateDecision,false);
assert.strictEqual(ready.requiredCashBuffer,9000);
assert.strictEqual(ready.cashReady,true);
assert.strictEqual(ready.recurringProfitReady,true);
assert.strictEqual(ready.noHiringAction,true);
assert.strictEqual(ready.noFinancialCommitment,true);
assert.strictEqual(ready.externalApiCostEur,0);
assert.strictEqual(ready.persistentStorage,false);
assert.strictEqual(ready.containsPersonalData,false);
const lowCash=g.evaluate(profile,{currentCash:5000,existingMonthlyCashExpenses:600,currentMonthlyOperatingResult:1200,positiveMonths:3,reserveMonths:6});
assert.strictEqual(lowCash.recommendation,'DELAY_HIRE');
assert(lowCash.reasons.includes('INSUFFICIENT_CASH_BUFFER'));
assert.strictEqual(lowCash.cashGap,4000);
assert.strictEqual(lowCash.monthsToCashBuffer,4);
const noHistory=g.evaluate(profile,{currentCash:10000,existingMonthlyCashExpenses:600,currentMonthlyOperatingResult:1200,positiveMonths:1,requiredPositiveMonths:3,reserveMonths:6});
assert.strictEqual(noHistory.recommendation,'DELAY_HIRE');
assert(noHistory.reasons.includes('INSUFFICIENT_POSITIVE_MONTHS'));
const weakProfile=g.evaluate({economicallyReady:false,monthlyCost:900,monthlyNetImpact:-1500},{currentCash:20000,existingMonthlyCashExpenses:600,currentMonthlyOperatingResult:500,positiveMonths:6,reserveMonths:6});
assert.strictEqual(weakProfile.recommendation,'DELAY_HIRE');
assert(weakProfile.reasons.includes('PROFILE_NOT_ECONOMICALLY_READY'));
assert(weakProfile.reasons.includes('POST_HIRE_RESULT_NEGATIVE'));
const html=fs.readFileSync(path.join(__dirname,'../frontend/hiring-runway-lab.html'),'utf8');
assert(html.includes('hire-runway-gate.js'));
assert(html.includes('DECISIÓN DEL FUNDADOR'));
assert(html.includes('FOUNDER_REVIEW'));
assert(html.includes('founder-hiring-kit.html'));
console.log('hire runway gate tests passed');
