const assert=require('assert');
require('../frontend/js/founder-capacity.js');
require('../frontend/js/hiring-model.js');
const c=globalThis.FIACOFounderCapacity;
const h=globalThis.FIACOHiringModel;
const items=Array.from({length:200},(_,i)=>({id:'X'+i,humanMinutes:12,automatedMinutes:8}));
const cap=c.analyze(items,{founderOpsHoursPerMonth:40,hireThresholdPct:80});
assert.strictEqual(cap.hiringSignal,'PREPARE_HIRE');
const result=h.evaluate(cap,'OPS_ASSISTANT',{revenuePerManagement:24,contributionRatePct:60,expectedUtilizationPct:70});
assert.strictEqual(result.noHiringAction,true);
assert.strictEqual(result.noFinancialCommitment,true);
assert.strictEqual(result.persistentStorage,false);
assert.strictEqual(result.containsPersonalData,false);
assert(result.addedCapacity>0);
assert(result.breakEvenAddedManagements>0);
const compared=h.compare(cap,{revenuePerManagement:24,contributionRatePct:60});
assert.strictEqual(compared.length,3);
assert(compared[0].monthlyNetImpact>=compared[1].monthlyNetImpact);
const lowCap=c.analyze(Array.from({length:10},()=>({humanMinutes:10,automatedMinutes:10})),{founderOpsHoursPerMonth:40,hireThresholdPct:80});
assert.strictEqual(h.evaluate(lowCap,'OPS_ASSISTANT').recommendation,'DELAY_HIRE');
console.log('hiring model tests passed');
