import fs from 'node:fs';
const html=fs.readFileSync(new URL('../frontend/index.html',import.meta.url),'utf8');
function ok(v,m){if(!v)throw new Error(m)}
ok(html.includes('name="viewport"'),'homepage must be mobile ready');
ok(html.includes('Content-Security-Policy'),'homepage must define CSP');
ok(!/<script(?![^>]*src=)[^>]*>/i.test(html),'homepage must not contain inline scripts');
ok(html.includes('id="que-resuelve"'),'homepage must explain user-facing needs');
ok(html.includes('id="seguridad"'),'homepage must explain public security principles');
ok(html.includes('id="contacto"'),'homepage must expose first-contact entry');
ok(html.includes('MENOS RUIDO.')&&html.includes('MÁS CONTROL.'),'homepage must keep a simple public proposition');
ok(html.includes('Primer contacto sin datos reales'),'homepage must communicate low-data entry');
ok(html.includes('FIA no recibe, custodia ni mueve fondos'),'homepage must preserve financial boundary');
ok(html.includes('js/fia-public-guide.js'),'homepage must use the minimal public guide');
ok(html.includes('js/fia-first-contact.js'),'homepage must load first-contact gate');
ok(html.includes('js/fia-human-presence.js'),'homepage must load lightweight presence signal');
ok(!html.includes('beta-mobile.html'),'homepage must not link deep beta app');
ok(!html.includes('app-beta.html'),'homepage must not link app redirect');
ok(!html.includes('integrations.html'),'homepage must not expose integration route');
ok(!html.includes('tx-advanced.html'),'homepage must not expose advanced route');
ok(!html.includes('Agente Premium'),'homepage must not expose internal/deep product surface');
ok(!html.includes('Cartera &amp;'),'homepage must not expose demo wallet surface');
ok(!/L[0-4]_(?:DEMO|ISOLATED|VERIFIED|SHARED|ADVANCED)/.test(html),'homepage must not expose internal trust codes');
ok(!html.includes('images.pexels.com'),'homepage must not load third-party hero imagery');
ok(html.includes('legal-center.html'),'homepage must link public legal information');
console.log('PASS homepage need-to-know public surface');
