const fs=require('fs'),assert=require('assert');
const p=JSON.parse(fs.readFileSync('config/legal-policy-architecture.json','utf8'));
const b=fs.readFileSync('docs/legal/LEGAL-2B-JURISDICTION-SOURCES.md','utf8');
const c=fs.readFileSync('docs/legal/LEGAL-2C-POLICY-ARCHITECTURE.md','utf8');
assert.equal(p.jurisdictionProfile,'ES-EU-RESEARCH');
assert.equal(p.jurisdictionValidated,false);
assert.equal(p.externalLegalReviewCompleted,false);
assert.equal(p.legalReadyForPilot,false);
assert.deepEqual(p.ruleKinds,['norm','case_law','internal_policy','recommendation']);
assert.equal(p.precedence.caseLawMayAutoEnforce,false);
assert.equal(p.humanInLoop.requiredForBindingLegalEffect,true);
assert.equal(p.rollback.supported,true);
assert.equal(p.enforcement.automatedLegalEnforcementEnabled,false);
assert.equal(p.enforcement.caseLawDirectEnforcementEnabled,false);
assert.equal(p.enforcement.premiumAgentMode,'shadow-read-only');
assert.equal(p.enforcement.realMoney,false); assert.equal(p.enforcement.realPii,false);
['España + marco de la Unión Europea','LSSI-CE','TRLGDCU','RGPD','eIDAS','DSA','AI Act','Jurisprudencia','Revisión profesional obligatoria'].forEach(x=>assert(b.includes(x),x));
['L2C-1','L2C-2','L2C-3','L2C-4','L2C-5','L2C-6','Human-in-the-loop','Rollback','shadow-read-only'].forEach(x=>assert(c.includes(x),x));
console.log('LEGAL-2B/2C architecture gate passed');
