const assert=require('assert');
require('../frontend/js/ops-automation.js');
const a=globalThis.FIACOOpsAutomation;
const normal={id:'1',alias:'Caso normal',pendingDocuments:0,requiresHuman:false,riskCount:0,closed:false};
const risky={id:'2',alias:'Caso riesgo',pendingDocuments:2,requiresHuman:true,riskCount:1,closed:false};
const closed={id:'3',alias:'Caso cerrado',pendingDocuments:0,requiresHuman:false,riskCount:0,closed:true};
assert.strictEqual(a.classify(normal).level,'LOW');
assert(['HIGH','CRITICAL'].includes(a.classify(risky).level));
assert.strictEqual(a.reminder(risky).needed,true);
assert.strictEqual(a.reminder(closed).needed,false);
const plan=a.plan(risky);
assert.strictEqual(plan.financialActionAllowed,false);
assert.strictEqual(plan.destructiveActionAllowed,false);
assert.strictEqual(plan.externalSendAllowed,false);
assert.strictEqual(plan.persistentStorage,false);
assert.strictEqual(plan.containsPersonalData,false);
assert(a.draft(risky).includes('revisión humana'));
const q=a.queue([normal,risky,closed]);
assert.strictEqual(q[0].id,'2');
const s=a.stats([normal,risky,closed]);
assert.strictEqual(s.items,3);
assert.strictEqual(s.financialActionAllowed,false);
assert.strictEqual(s.externalSendAllowed,false);
assert.strictEqual(s.persistentStorage,false);
console.log('ops automation tests passed');
