const assert=require('assert');
require('../frontend/js/agent-security.js');
require('../frontend/js/enterprise-flow.js');
require('../frontend/js/ops-metrics.js');
let flow=globalThis.FIACOEnterpriseFlow.create({company:'Empresa Demo',description:'Compraventa de vehículo con documentación pendiente'});
flow=globalThis.FIACOEnterpriseFlow.advance(flow);
flow.documents.forEach((_,i)=>globalThis.FIACOEnterpriseFlow.setDocument(flow,i,true));
flow=globalThis.FIACOEnterpriseFlow.advance(flow);
flow=globalThis.FIACOEnterpriseFlow.advance(flow);
if(flow.state==='HUMAN_REVIEW') flow=globalThis.FIACOEnterpriseFlow.advance(flow);
const summary=globalThis.FIACOEnterpriseFlow.summary(flow);
let bucket=globalThis.FIACOOpsMetrics.empty();
bucket=globalThis.FIACOOpsMetrics.add(bucket,summary);
const report=globalThis.FIACOOpsMetrics.report(bucket);
assert.strictEqual(report.operations,1);
assert.strictEqual(report.containsPersonalData,false);
assert.strictEqual(report.persistentStorage,false);
assert(report.automationPct>=0&&report.automationPct<=100);
assert(!('company' in report));
assert(!('description' in report));
console.log('ops metrics tests passed');
