const assert=require('assert');
require('../frontend/js/agent-security.js');
require('../frontend/js/enterprise-flow.js');
require('../frontend/js/enterprise-ops-dashboard.js');
require('../frontend/js/pricing.js');
require('../frontend/js/ops-hub.js');
const hub=globalThis.FIACOOpsHub;
let flow=globalThis.FIACOEnterpriseFlow.create({company:'Empresa Demo',description:'Compraventa de vehículo con documentación pendiente'});
flow=globalThis.FIACOEnterpriseFlow.advance(flow);
const item=hub.toPortfolioItem(flow,{alias:'Caso demo',segment:'TRANSPORT',amount:8000,createdAt:1700000000000});
assert.strictEqual(item.containsPersonalData,false);
assert.strictEqual(item.persistentStorage,false);
assert(!('company' in item));
assert(!('description' in item));
const report=hub.aggregate([item],'ALL',1700000000000);
assert.strictEqual(report.operations,1);
assert.strictEqual(report.containsPersonalData,false);
assert.strictEqual(report.noFinancialAuthority,true);
const projected=hub.project([item],{referenceNow:1700000000000,revenuePerManagement:24,operationsM12:300,automationM12:85,expenseM1:600,expenseM12:1325});
assert.strictEqual(projected.containsPersonalData,false);
assert.strictEqual(projected.productionExecutionEnabled,false);
assert.strictEqual(projected.noFinancialAuthority,true);
assert.strictEqual(projected.simulation.dataSource,'UNIFIED_OPS_AGGREGATE');
assert.strictEqual(projected.simulation.productionBillingEnabled,false);
assert.throws(()=>hub.project([],{}),/Falta muestra operativa/);
console.log('ops hub tests passed');
