const assert=require('assert');
require('../frontend/js/production-gate.js');
const g=globalThis.FIACOProductionGate;
const blocked=g.evaluate({});
assert.strictEqual(blocked.status,'BLOCKED_DEMO_ONLY');
assert.strictEqual(blocked.productionExecutionEnabled,false);
assert.strictEqual(blocked.realFundsEnabled,false);
assert.strictEqual(blocked.realPiiEnabled,false);
assert.strictEqual(blocked.newAuthorizationRequired,false);
const all={};g.checks.forEach(k=>all[k]=true);const ready=g.evaluate(all);
assert.strictEqual(ready.status,'READY_FOR_EXPLICIT_PRODUCTION_AUTHORIZATION');
assert.strictEqual(ready.prerequisitesReady,true);
assert.strictEqual(ready.newAuthorizationRequired,true);
assert.strictEqual(ready.productionExecutionEnabled,false);
assert.strictEqual(ready.realFundsEnabled,false);
assert.strictEqual(ready.billingEnabled,false);
assert.strictEqual(ready.explicitFounderAuthorizationRequired,true);
assert.strictEqual(ready.noAutomaticActivation,true);
console.log('production gate tests passed');
