import fs from 'node:fs';
import assert from 'node:assert/strict';
import {assessSecureIntake} from '../core/pilot/secure-intake.mjs';
const manifest=JSON.parse(fs.readFileSync('config/secure-intake-manifest.v1.json','utf8'));
const empty=assessSecureIntake(manifest);
assert.equal(empty.total,28);
assert.equal(empty.pending,28);
assert.equal(empty.decision,'KEEP_REAL_USERS_BLOCKED');
assert.deepEqual(empty.groups,{OWNER_NOW:8,PRIVACY_DECISIONS:7,PSP_LATER:4,INFRA_LATER:5,HUMAN_BEFORE:4});
assert.equal(empty.gates.PUBLIC_SERVICE.ready,false);
assert.equal(empty.gates.REAL_PREPILOT.ready,false);
assert.equal(empty.gates.PAYMENT_PILOT.ready,false);
const statuses=Object.fromEntries(manifest.items.map(x=>[x.id,{status:x.kind==='DOCUMENT_OR_NA'?'NOT_APPLICABLE_VERIFIED':x.kind.includes('DOCUMENT')?'DOCUMENT_RECEIVED':'CONFIRMED'}]));
const complete=assessSecureIntake(manifest,statuses);
assert.equal(complete.completed,28);
assert.equal(complete.gates.REAL_PREPILOT.ready,true);
assert.equal(complete.gates.PAYMENT_PILOT.ready,true);
assert.equal(complete.decision,'READY_FOR_PROFESSIONAL_AND_TECHNICAL_REVIEW');
assert.equal(complete.realUserAccessEnabled,false);
assert.throws(()=>assessSecureIntake(manifest,{API_KEY:{status:'CONFIRMED'}}),/SECRET_MUST_NOT_BE_SUBMITTED/);
assert.throws(()=>assessSecureIntake(manifest,{LEGAL_NAME:{status:'CONFIRMED',value:'raw'}}),/RAW_VALUES_NOT_ACCEPTED/);
console.log('secure-intake: ok');
