(function(global){'use strict';
const VERSION='0.1-demo';
const STATES=['NEW','CLASSIFIED','DOCUMENTS_PENDING','READY_FOR_REVIEW','HUMAN_REVIEW','CLOSED_SIMULATED'];
function safe(v,max){return String(v||'').replace(/[<>]/g,'').trim().slice(0,max||160)}
function create(input){input=input||{};const company=safe(input.company,80);const description=safe(input.description,800);if(company.length<2)throw new Error('Empresa no válida');if(description.length<5)throw new Error('Descripción demasiado corta');const security=global.FIACOAgentSecurity.process(description);const docs=[];if(/veh[ií]culo|coche|moto/i.test(description))docs.push('Identificación de las partes','Documento del bien','Condiciones de compraventa');else docs.push('Identificación de las partes','Documento/contrato de la gestión');return {id:'MGT-'+Math.random().toString(36).slice(2,9).toUpperCase(),company,description,state:'NEW',category:security.category,riskFlags:security.riskFlags,requiresHuman:security.humanApprovalRequired,documents:docs.map(name=>({name,complete:false})),history:[{state:'NEW',note:'Gestión creada'}],metrics:{estimatedManualMinutes:security.telemetry.estimatedManualMinutes,estimatedHumanMinutes:security.telemetry.estimatedHumanMinutes,automatedMinutes:security.telemetry.automatedMinutes,automationPct:security.telemetry.automationPct},productionExecutionEnabled:false,noFinancialAuthority:true};}
function advance(flow){if(!flow||!STATES.includes(flow.state))throw new Error('Gestión no válida');let next=flow.state;let note='';if(flow.state==='NEW'){next='CLASSIFIED';note='Clasificación segura completada';}else if(flow.state==='CLASSIFIED'){next=flow.documents.every(d=>d.complete)?'READY_FOR_REVIEW':'DOCUMENTS_PENDING';note=next==='DOCUMENTS_PENDING'?'Falta documentación':'Documentación completa';}else if(flow.state==='DOCUMENTS_PENDING'){if(!flow.documents.every(d=>d.complete))return flow;next='READY_FOR_REVIEW';note='Documentación completada';}else if(flow.state==='READY_FOR_REVIEW'){next=flow.requiresHuman?'HUMAN_REVIEW':'CLOSED_SIMULATED';note=flow.requiresHuman?'Escalado a revisión humana':'Cierre simulado automático permitido';}else if(flow.state==='HUMAN_REVIEW'){next='CLOSED_SIMULATED';note='Cierre simulado aprobado por humano';}flow.state=next;if(note)flow.history.push({state:next,note});return flow;}
function setDocument(flow,index,complete){if(!flow||!flow.documents[index])throw new Error('Documento inválido');flow.documents[index].complete=!!complete;return flow;}
function summary(flow){const complete=flow.documents.filter(d=>d.complete).length;return {id:flow.id,state:flow.state,company:flow.company,category:flow.category,riskFlags:flow.riskFlags,documentsComplete:complete,documentsTotal:flow.documents.length,requiresHuman:flow.requiresHuman,metrics:flow.metrics,productionExecutionEnabled:false,noFinancialAuthority:true};}
global.FIACOEnterpriseFlow={version:VERSION,states:STATES,create,advance,setDocument,summary};
})(typeof window!=='undefined'?window:globalThis);
