(()=>{
'use strict';
const ALERT_KEY='fia_guide_alerts_v1';
const APP_KEY='fia_unified_beta_v2';
const MAX_ALERTS=12;
const el=(s,r=document)=>r.querySelector(s);
const els=(s,r=document)=>[...r.querySelectorAll(s)];
const norm=(v)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim().slice(0,1600);
const esc=(v)=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
const appMode=()=>document.body.classList.contains('unified-app');
const now=()=>new Date().toISOString();
const severityRank={info:0,warning:1,high:2,critical:3};

function loadAlerts(){try{const x=JSON.parse(sessionStorage.getItem(ALERT_KEY)||'[]');return Array.isArray(x)?x.slice(0,MAX_ALERTS):[];}catch(_e){return[];}}
let alerts=loadAlerts();
function saveAlerts(){try{sessionStorage.setItem(ALERT_KEY,JSON.stringify(alerts.slice(0,MAX_ALERTS)));}catch(_e){}}
function actualSensitiveValue(raw){const t=String(raw||'');return /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i.test(t)||/\bES\d{22}\b/i.test(t.replace(/\s+/g,''))||/\b(?:\d{8}[A-Z]|[XYZ]\d{7}[A-Z])\b/i.test(t)||/\b(?:api[_ -]?key|token|secret|password|contrasena)\s*[:=]\s*\S{6,}/i.test(t);}
function interactionRisks(raw){const t=norm(raw),out=[];const push=(code,severity,title,message)=>out.push({code,severity,title,message});
 if(actualSensitiveValue(raw))push('REAL_SENSITIVE_VALUE_DETECTED','critical','Dato real o secreto detectado','No continúes con ese valor en la demo. Sustitúyelo por información ficticia.');
 if(/\b(contrasena|password|credencial|api key|token|secreto|secret)\b/.test(t))push('CREDENTIAL_TOPIC_DETECTED','high','Credencial o secreto','Las credenciales no deben introducirse en el asistente ni en contexto de IA.');
 if(/(mueve|mover|mueva|muevas|movimiento de|custodia|custodiar|custodie|custodi[eoa]|transfiere|transferir|transfiera|transfieran|retira|retirar|retire|paga desde fia|pague desde fia|cobra desde fia|cobre desde fia).*(fondos|dinero|cuenta|pago)?/.test(t))push('FINANCIAL_EXECUTION_REQUEST','critical','Frontera financiera','FIA no recibe, custodia ni mueve fondos.');
 if(/(comparte|compartir|envia|enviar|dar acceso|acceso a).*(proveedor|taller|partner|otra empresa|tercero)/.test(t))push('CROSS_ORG_ACCESS_REQUEST','high','Acceso entre empresas','La compartición interempresa requiere controles específicos y, en FIA, al menos L3_SHARED.');
 if(/(garantiza ventas|roi garantizado|100% seguro|cumple todo|cumplimiento garantizado|sin ningun riesgo)/.test(t))push('UNSUPPORTED_ASSURANCE_CLAIM','warning','Afirmación demasiado absoluta','Conviene reformularla con evidencia y límites, no como una garantía.');
 return out.sort((a,b)=>severityRank[b.severity]-severityRank[a.severity]);}
function routeFor(raw){const t=norm(raw);
 if(/presupuesto|oferta|seguimiento|cliente olvidado/.test(t))return{title:'Quote Recovery',copy:'FIA puede mostrar cómo evitar que presupuestos u oportunidades queden sin seguimiento y qué métricas medir.',view:'operations',mood:'success'};
 if(/documento|papel|expediente|falta documentacion|renting/.test(t))return{title:'Document Flow',copy:'Podemos representar qué documento falta, quién debe aportarlo y qué bloquea la operación.',view:'evidence',mood:'success'};
 if(/proveedor|taller|partner|otra empresa|coordinacion|coordinación/.test(t))return{title:'Partner Coordination',copy:'FIA puede enseñar el flujo, pero la compartición real entre empresas permanece bloqueada hasta que exista el nivel de seguridad adecuado.',view:'logistics',mood:'warning'};
 if(/seguridad|permiso|acceso|quien ve|quién ve|nivel/.test(t))return{title:'Seguridad y acceso',copy:'FIA aumenta capacidad solo cuando aumentan antes los controles verificados. El acceso es una consecuencia del nivel de seguridad.',view:'identity',mood:'success'};
 if(/pago|banco|fondos|dinero|custodia/.test(t))return{title:'Frontera financiera',copy:'FIA coordina estados y evidencias, pero no recibe, custodia ni mueve fondos.',view:'wallet',mood:'warning'};
 if(/operacion|operación|trazabilidad|evento|evidencia/.test(t))return{title:'Trust Transaction',copy:'Podemos mostrar una operación trazable con permisos, estados, evidencias y revisión humana.',view:'operations',mood:'success'};
 return{title:'Explora FIA',copy:'Describe brevemente qué quieres resolver o ver. FIA te llevará al área más útil sin convertir la conversación en un cuestionario.',view:null,mood:'info'};}
function avatarHtml(){return '<span class="fia-guide-avatar" aria-hidden="true"><span class="fia-guide-mouth"></span></span>';}
function build(){if(el('.fia-guide-root'))return;const root=document.createElement('div');root.className='fia-guide-root';root.dataset.mood='info';root.innerHTML=`<button class="fia-guide-launcher" type="button" aria-label="Abrir copiloto FIA" aria-expanded="false">${avatarHtml()}<span class="fia-guide-badge" data-fia-alert-badge hidden>0</span></button><section class="fia-guide-panel" aria-label="Copiloto FIA" hidden><header class="fia-guide-head">${avatarHtml()}<div><strong>FIA · Copiloto</strong><small>Explora, no te interroga</small></div><button class="fia-guide-close" type="button" aria-label="Cerrar">×</button></header><div class="fia-guide-screen" data-fia-screen data-state="info"><small>LISTO</small><strong>¿Qué quieres resolver o ver?</strong><p>Escribe una situación y te llevo al área más útil de FIA.</p></div><form class="fia-guide-search" data-fia-search><input type="search" maxlength="280" autocomplete="off" placeholder="Ej. presupuestos sin seguimiento" aria-label="Buscar o conversar con FIA"><button type="submit">Ver</button></form><div class="fia-guide-chips"><button class="fia-guide-chip" type="button" data-fia-query="presupuestos sin seguimiento">Presupuestos</button><button class="fia-guide-chip" type="button" data-fia-query="documentos pendientes">Documentos</button><button class="fia-guide-chip" type="button" data-fia-query="seguridad y permisos">Seguridad</button><button class="fia-guide-chip" type="button" data-fia-query="operación trazable">Operación</button></div><p class="fia-guide-context-note">Modo demo. No pegues datos reales, contraseñas, tokens ni información bancaria. El texto de búsqueda no se guarda.</p><div class="fia-guide-alerts"><div class="fia-guide-alerts-head"><strong>Alertas detectadas <span data-fia-alert-count>0</span></strong><button class="fia-guide-clear" type="button">Limpiar avisos</button></div><div class="fia-guide-alert-list" data-fia-alert-list></div></div></section><div class="fia-guide-toast-region" data-fia-toast-region aria-live="assertive" aria-atomic="false"></div>`;document.body.append(root);bind(root);renderAlerts(root);scanAppState(root);}
function setScreen(root,title,copy,mood='info'){const screen=el('[data-fia-screen]',root);if(!screen)return;root.dataset.mood=mood;screen.dataset.state=mood;el('small',screen).textContent=mood==='critical'?'RIESGO CRÍTICO':mood==='high'?'RIESGO DETECTADO':mood==='warning'?'ATENCIÓN':'FIA';el('strong',screen).textContent=title;el('p',screen).textContent=copy;}
function openPanel(root,open=true){const p=el('.fia-guide-panel',root),b=el('.fia-guide-launcher',root);p.hidden=!open;b.setAttribute('aria-expanded',String(open));}
function toast(root,a){if(severityRank[a.severity]<1)return;const host=el('[data-fia-toast-region]',root);const node=document.createElement('div');node.className=`fia-guide-toast ${a.severity}`;node.innerHTML=`<strong>${esc(a.title)}</strong><span>${esc(a.message)}</span>`;host.append(node);setTimeout(()=>node.remove(),5200);if(a.severity==='critical'&&navigator.vibrate)try{navigator.vibrate([100,60,100]);}catch(_e){}}
function addAlert(root,a){const key=`${a.code}:${a.subject||''}`;if(alerts.some(x=>x.key===key&&Date.now()-new Date(x.at).getTime()<120000))return;const safe={key,code:a.code,severity:a.severity,title:a.title,message:a.message,subject:a.subject||null,at:now()};alerts.unshift(safe);alerts=alerts.slice(0,MAX_ALERTS);saveAlerts();renderAlerts(root);toast(root,safe);root.dataset.mood=safe.severity;}
function renderAlerts(root){const host=el('[data-fia-alert-list]',root),count=el('[data-fia-alert-count]',root),badge=el('[data-fia-alert-badge]',root);if(!host)return;host.replaceChildren();count.textContent=String(alerts.length);badge.textContent=String(alerts.length);badge.hidden=alerts.length===0;if(!alerts.length){const p=document.createElement('p');p.className='fia-guide-context-note';p.textContent='Sin alertas activas en esta sesión.';host.append(p);return;}alerts.forEach(a=>{const node=document.createElement('article');node.className=`fia-guide-alert-item ${a.severity}`;node.innerHTML=`<strong>${esc(a.title)}</strong><p>${esc(a.message)}</p><time>${new Intl.DateTimeFormat('es-ES',{hour:'2-digit',minute:'2-digit'}).format(new Date(a.at))}</time>`;host.append(node);});}
function navigate(view){if(!view)return;if(appMode()){const target=el(`[data-view-target="${view}"]`);target?.click();}else if(view==='identity'||view==='wallet'){location.href='beta-mobile.html';}else location.href='beta-mobile.html';}
function submit(root,raw){root.dataset.mood='thinking';setTimeout(()=>{const risks=interactionRisks(raw);if(risks.length){risks.forEach(r=>addAlert(root,r));const top=risks[0];setScreen(root,top.title,top.message,top.severity);return;}const route=routeFor(raw);setScreen(root,route.title,route.copy,route.mood);const screen=el('[data-fia-screen]',root);if(route.view){const btn=document.createElement('button');btn.type='button';btn.className='fia-guide-chip';btn.textContent=appMode()?'Abrir esta área':'Abrir en la app';btn.addEventListener('click',()=>navigate(route.view));screen.append(btn);}},260);}
function bind(root){el('.fia-guide-launcher',root).addEventListener('click',()=>openPanel(root,el('.fia-guide-panel',root).hidden));el('.fia-guide-close',root).addEventListener('click',()=>openPanel(root,false));el('[data-fia-search]',root).addEventListener('submit',e=>{e.preventDefault();const input=el('input',e.currentTarget);submit(root,input.value);input.value='';});els('[data-fia-query]',root).forEach(b=>b.addEventListener('click',()=>submit(root,b.dataset.fiaQuery)));el('.fia-guide-clear',root).addEventListener('click',()=>{alerts=[];saveAlerts();renderAlerts(root);root.dataset.mood='info';});document.addEventListener('invalid',e=>{if(!e.target.closest?.('form'))return;addAlert(root,{code:'FORM_VALIDATION_ERROR',severity:'warning',title:'Falta información obligatoria',message:'Revisa los campos marcados antes de continuar.'});},true);document.addEventListener('input',e=>{const node=e.target;if(!node.matches?.('input[type="text"],input[type="email"],input[type="search"],textarea'))return;if(actualSensitiveValue(node.value))addAlert(root,{code:'REAL_SENSITIVE_VALUE_DETECTED',severity:'critical',title:'Dato real o secreto detectado',message:'No continúes con ese valor en la demo. Sustitúyelo por información ficticia.'});},true);window.addEventListener('error',()=>addAlert(root,{code:'UI_RUNTIME_ERROR',severity:'high',title:'Error de interfaz detectado',message:'FIA ha detectado un error de ejecución. Revisa la acción antes de continuar.'}));window.addEventListener('unhandledrejection',()=>addAlert(root,{code:'UI_ASYNC_ERROR',severity:'high',title:'Error de proceso detectado',message:'Una operación de interfaz no terminó correctamente. Revisa antes de continuar.'}));window.addEventListener('storage',e=>{if(e.key===APP_KEY)scanAppState(root);});if(appMode())setInterval(()=>scanAppState(root),1800);}
function scanAppState(root){if(!appMode())return;let s;try{s=JSON.parse(localStorage.getItem(APP_KEY)||'null');}catch(_e){addAlert(root,{code:'APP_STATE_INVALID',severity:'high',title:'Estado local dañado',message:'No se puede interpretar el estado demo. Conviene restablecer la demo antes de seguir.'});return;}if(!s||!Array.isArray(s.operations)||!Array.isArray(s.evidence))return;s.operations.forEach(op=>{const ev=s.evidence.filter(x=>x.operationId===op.id);const incident=ev.some(x=>x.type==='Incidencia');const needs=['sale_transport','transport','special','animal'].includes(op.type);if(incident)addAlert(root,{code:'OPERATION_INCIDENT_OPEN',subject:op.id,severity:'high',title:`Incidencia · ${op.reference||'operación'}`,message:'Existe una incidencia registrada y requiere revisión humana.'});if(op.completed&&incident)addAlert(root,{code:'COMPLETED_WITH_OPEN_INCIDENT',subject:op.id,severity:'critical',title:`Cierre inconsistente · ${op.reference||'operación'}`,message:'La operación figura cerrada mientras existe una incidencia.'});else if(op.completed&&!ev.length)addAlert(root,{code:'COMPLETED_WITHOUT_EVIDENCE',subject:op.id,severity:'high',title:`Cierre sin evidencia · ${op.reference||'operación'}`,message:'La operación figura cerrada sin evidencia vinculada.'});else if(needs&&!op.logistics)addAlert(root,{code:'LOGISTICS_PLAN_MISSING',subject:op.id,severity:'warning',title:`Logística pendiente · ${op.reference||'operación'}`,message:'Esta operación requiere logística y todavía no tiene plan.'});});}
window.FIAGuide=Object.freeze({open(){const r=el('.fia-guide-root');if(r)openPanel(r,true);},alert(input={}){const r=el('.fia-guide-root');if(r)addAlert(r,{code:String(input.code||'EXTERNAL_ALERT').slice(0,80),severity:['warning','high','critical'].includes(input.severity)?input.severity:'warning',title:String(input.title||'Aviso FIA').slice(0,120),message:String(input.message||'Revisa esta acción antes de continuar.').slice(0,260)});},evaluateText:text=>Object.freeze({risks:interactionRisks(text),route:routeFor(text),inputStored:false})});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build,{once:true});else build();
})();