(()=>{'use strict';
const f=(name,label,type='text',required=true,extra={})=>({name,label,type,required,...extra});
const common={partyA:[f('partyA','Parte solicitante / empresa'),f('partyAId','NIF o identificador')],partyB:[f('partyB','Contraparte / proveedor'),f('partyBId','NIF o identificador')]};
const MODELS=[
{id:'vehicle-sale',title:'Compraventa de vehículo',group:'Contratos',status:'REVISIÓN JURÍDICA PENDIENTE',description:'Contrato preparado con los datos mínimos indicados por la DGT y campos operativos FIA&CO.',fields:[f('seller','Vendedor: nombre o razón social'),f('sellerId','DNI/NIE/NIF del vendedor'),f('buyer','Comprador: nombre o razón social'),f('buyerId','DNI/NIE/NIF del comprador'),f('brandModel','Marca y modelo'),f('plate','Matrícula'),f('vin','Número de bastidor'),f('mileage','Kilometraje', 'number'),f('price','Precio acordado (€)','number'),f('signedAt','Fecha y hora de firma','datetime-local'),f('delivery','Lugar y condiciones de entrega'),f('condition','Estado, defectos conocidos y accesorios','textarea'),f('charges','Cargas, impuestos o limitaciones declaradas','textarea'),f('payment','Proveedor de pago o forma acordada'),f('observations','Observaciones','textarea',false)],clauses:['El vendedor se obliga a entregar el vehículo descrito y el comprador a pagar el precio cierto indicado.','Las partes declaran haber revisado la identidad, titularidad, estado, cargas, documentación y condiciones reflejadas en el borrador.','El cambio de titularidad, tributos y notificación de venta se tramitarán ante los organismos competentes.','FIA&CO organiza información y trazabilidad; no recibe, custodia ni mueve fondos.']},
{id:'b2b-goods',title:'Compraventa mercantil B2B',group:'Contratos',status:'REVISIÓN JURÍDICA PENDIENTE',description:'Bienes entre empresas con condiciones, entrega, evidencias e incid incidencias.',fields:[...common.partyA,...common.partyB,f('object','Bienes y cantidades','textarea'),f('price','Precio e impuestos','text'),f('payment','Proveedor de pago y condición de liberación'),f('delivery','Entrega, plazo e Incoterm si procede','textarea'),f('acceptance','Criterios de aceptación','textarea'),f('warranty','Garantía o responsabilidad acordada','textarea'),f('law','Ley y jurisdicción propuestas', 'text',false)],clauses:['Las partes acuer cumplirán las condiciones descritas y documentarán entrega y aceptación.','Toda incidencia suspende el cierre automático y requiere revisión humana.','FIA&CO no es parte vendedora, compradora ni proveedor de pagos.']},
{id:'b2b-service',title:'Encargo de servicios B2B',group:'Contratos',status:'REVISIÓN JURÍDICA PENDIENTE',description:'Alcance, hitos, aceptación y cierre de un servicio profesional.',fields:[...common.partyA,...common.partyB,f('scope','Alcance del servicio','textarea'),f('deliverables','Entregables e hitos','textarea'),f('price','Precio, impuestos y facturación'),f('dates','Fechas y plazos'),f('acceptance','Criterios de aceptación','textarea'),f('confidentiality','Necesidades de confidencialidad','textarea',false),f('termination','Condiciones de cancelación','textarea',false)],clauses:['El proveedor realizará únicamente el alcance y entregables descritos.','Los cambios requieren confirmación trazable de ambas partes.','La aceptación y cualquier incidencia relevante requieren intervención humana.']},
{id:'quote-followup',title:'Presupuesto y seguimiento',group:'Comercial',status:'OPERATIVO DEMO',description:'Solicitud, propuesta, vencimiento y próximo contacto.',fields:[f('company','Empresa interesada'),f('contactRole','Cargo o función, sin datos innecesarios'),f('need','Necesidad descrita','textarea'),f('proposal','Solución y alcance propuestos','textarea'),f('amount','Importe estimado'),f('validUntil','Válido hasta','date'),f('nextStep','Siguiente acción'),f('owner','Responsable interno')],clauses:['Documento comercial no vinculante salvo aceptación expresa.','No incluir categorías especiales de datos ni información innecesaria.']},
{id:'purchase-request',title:'Solicitud de compra y comparación',group:'Compras',status:'OPERATIVO DEMO',description:'Necesidad, criterios objetivos, fuentes y declaración de patrocinios.',fields:[f('requester','Empresa solicitante'),f('item','Producto o servicio buscado'),f('specs','Requisitos imprescindibles','textarea'),f('budget','Presupuesto máximo', 'text',false),f('deadline','Fecha límite','date'),f('criteria','Criterios y ponderación','textarea'),f('sources','Fuentes autorizadas','textarea'),f('sponsorship','Patrocinios o conflictos declarados','textarea',false)],clauses:['La comparación debe mostrar fuentes, criterios y limitaciones.','Un patrocinio no mejora la puntuación del resultado.','La decisión final corresponde al usuario.']},
{id:'transport-order',title:'Orden de transporte o entrega',group:'Logística',status:'REVISIÓN SECTORIAL PENDIENTE',description:'Recogida, entrega, bulto, responsable y condiciones especiales.',fields:[f('shipper','Empresa expedidora'),f('carrier','Transportista propuesto'),f('origin','Origen'),f('destination','Destino'),f('goods','Descripción, cantidad, peso y medidas','textarea'),f('pickup','Fecha de recogida','datetime-local'),f('delivery','Fecha prevista de entrega','datetime-local'),f('handling','Manipulación o requisitos especiales','textarea',false),f('reference','Referencia de operación FIA'),f('insurance','Seguro o cobertura declarada','text',false)],clauses:['El transportista debe acreditar habilitación cuando resulte exigible.','Los requisitos especiales no se presumen aceptados hasta confirmación del proveedor.','No utilizar este modelo para animales o mercancías especiales sin activar su revisión sectorial.']},
{id:'evidence-handover',title:'Acta de entrega y evidencias',group:'Operación',status:'OPERATIVO DEMO',description:'Registra qué se entrega, cuándo y qué evidencia queda asociada.',fields:[f('operation','Referencia FIA'),f('sender','Parte que entrega'),f('receiver','Parte que recibe'),f('deliveredAt','Fecha y hora','datetime-local'),f('items','Elementos entregados','textarea'),f('condition','Estado observado','textarea'),f('evidence','Referencias de fotos o documentos, sin adjuntarlos aquí','textarea',false),f('reservations','Reservas o discrepancias','textarea',false)],clauses:['El acta registra declaraciones y referencias; no demuestra por sí sola la autenticidad.','Las contradicciones bloquean el cierre y se derivan a revisión humana.']},
{id:'incident-report',title:'Comunicación de incidencia',group:'Operación',status:'OPERATIVO DEMO',description:'Hechos, impacto, evidencias disponibles y medida provisional.',fields:[f('operation','Referencia FIA'),f('reporter','Parte que comunica'),f('detectedAt','Fecha y hora de detección','datetime-local'),f('category','Tipo de incidencia'),f('facts','Hechos observados, sin opiniones','textarea'),f('impact','Impacto conocido','textarea'),f('evidence','Referencias de evidencia','textarea',false),f('containment','Medida provisional solicitada','textarea'),f('contact','Canal seguro de seguimiento','text',false)],clauses:['La apertura de una incidencia no determina responsabilidad.','FIA&CO no decide automáticamente quién tiene razón.','Conservar únicamente la información necesaria para investigar.']},
{id:'provider-qualification',title:'Alta de proveedor cualificado',group:'Proveedores',status:'REVISIÓN PROFESIONAL PENDIENTE',description:'Capacidad, habilitación, seguridad, protección de datos y condiciones.',fields:[f('provider','Razón social'),f('taxId','NIF / VAT'),f('service','Servicio ofrecido'),f('territory','Países y territorio'),f('license','Licencia, registro o habilitación aplicable','textarea'),f('insurance','Seguro y cobertura','textarea',false),f('security','Controles de seguridad declarados','textarea'),f('privacy','Rol RGPD y garantías','textarea'),f('subprocessors','Subcontratistas relevantes','textarea',false),f('sla','Disponibilidad, soporte y SLA','textarea'),f('pricing','Precios y costes','textarea'),f('contact','Canal profesional')],clauses:['La recepción de este formulario no supone homologación ni autorización por FIA&CO.','La documentación deberá verificarse por fuente independiente y por el profesional responsable.','No introducir claves, contraseñas ni secretos técnicos.']},
{id:'payment-provider',title:'Conexión con proveedor de pago',group:'Proveedores',status:'SANDBOX / PRODUCCIÓN BLOQUEADA',description:'Requisitos de un PSP o banco autorizado sin recoger credenciales secretas.',fields:[f('provider','Entidad o PSP'),f('legalStatus','Licencia y supervisor'),f('merchant','Identificador comercial'),f('flow','Flujo de autorización, captura, devolución y conciliación','textarea'),f('kyb','Requisitos KYB/KYC','textarea'),f('webhooks','Eventos y firma de webhooks','textarea'),f('settlement','Liquidación directa entre proveedor y partes','textarea'),f('support','Soporte e incidencias'),f('secretRef','Referencia de bóveda; nunca el secreto','text',false)],clauses:['Las claves se gestionan exclusivamente en una bóveda del servidor.','FIA&CO no recibe, custodia ni mueve fondos.','Producción permanece bloqueada hasta contrato, revisión legal, seguridad y pruebas sandbox.']},
{id:'document-request',title:'Solicitud controlada de documentación',group:'Documentación',status:'OPERATIVO DEMO',description:'Pide solo el documento necesario, con finalidad, acceso y borrado.',fields:[f('operation','Referencia FIA'),f('requester','Quién solicita'),f('holder','Quién debe aportarlo'),f('document','Documento o evidencia solicitada'),f('purpose','Finalidad concreta'),f('legalBasis','Base o necesidad operativa'),f('access','Personas o funciones con acceso'),f('deadline','Fecha límite','date'),f('retention','Plazo de conservación y borrado')],clauses:['Solicitar la mínima información necesaria.','No reutilizar el documento para otra finalidad sin base válida.','El acceso y la conservación deben limitarse al proceso.']},
{id:'operation-close',title:'Acta de cierre de operación',group:'Operación',status:'OPERATIVO DEMO',description:'Resultado, entregas, incidencias y tareas posteriores.',fields:[f('operation','Referencia FIA'),f('parties','Partes participantes','textarea'),f('outcome','Resultado acordado','textarea'),f('delivery','Entrega y aceptación','textarea'),f('paymentStatus','Estado comunicado por el proveedor de pago'),f('incidents','Incidencias y resolución humana','textarea',false),f('pending','Obligaciones pendientes','textarea',false),f('closedAt','Fecha y hora de cierre','datetime-local'),f('reviewer','Persona que revisa')],clauses:['El cierre refleja el estado declarado y no sustituye obligaciones legales o fiscales.','Cualquier discrepancia abierta impide marcar el cierre como definitivo.']}
];
const $=s=>document.querySelector(s),list=$('[data-model-list]'),form=$('[data-model-form]'),title=$('[data-model-title]'),description=$('[data-model-description]'),status=$('[data-model-status]'),preview=$('[data-preview]'),message=$('[data-message]');let current=null,draft='';
function button(m){const b=document.createElement('button');b.type='button';b.dataset.model=m.id;b.innerHTML='<b></b><span></span>';b.querySelector('b').textContent=m.title;b.querySelector('span').textContent=m.group;b.addEventListener('click',()=>select(m.id));return b;}
function renderList(q=''){list.replaceChildren();const n=q.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');for(const m of MODELS.filter(x=>(x.title+' '+x.group+' '+x.description).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').includes(n)))list.append(button(m));}
function select(id){current=MODELS.find(x=>x.id===id)||MODELS[0];title.textContent=current.title;description.textContent=current.description;status.textContent=current.status;form.replaceChildren();for(const field of current.fields){const label=document.createElement('label'),control=document.createElement(field.type==='textarea'?'textarea':'input');label.textContent=field.label;control.name=field.name;control.required=field.required;control.autocomplete='off';if(control.tagName==='INPUT')control.type=field.type;label.append(control);form.append(label);}document.querySelectorAll('[data-model]').forEach(b=>b.classList.toggle('active',b.dataset.model===current.id));clearOutput();history.replaceState(null,'',`?model=${encodeURIComponent(current.id)}`);}
function clearOutput(){draft='';preview.hidden=true;preview.textContent='';message.textContent='Completa los campos obligatorios para generar el borrador.';['copy','download','print'].forEach(x=>$('[data-'+x+']').disabled=true);}
function buildDraft(){if(!current)return'';if(!form.reportValidity())return'';const data=new FormData(form),lines=[`FIA&CO · ${current.title}`,current.status,'',current.description,''];for(const field of current.fields)lines.push(`${field.label}: ${String(data.get(field.name)||'—').trim()||'—'}`);lines.push('','CONDICIONES DEL BORRADOR');current.clauses.forEach((x,i)=>lines.push(`${i+1}. ${x}`));lines.push('','FIRMA / CONFIRMACIÓN DE LAS PARTES: ______________________________','','Documento generado localmente. FIA&CO no ha recibido ni almacenado estos datos.');return lines.join('\n');}
$('[data-generate]').addEventListener('click',()=>{draft=buildDraft();if(!draft){message.textContent='Faltan campos obligatorios.';return;}preview.textContent=draft;preview.hidden=false;message.textContent='Borrador generado localmente. Revísalo antes de descargarlo.';['copy','download','print'].forEach(x=>$('[data-'+x+']').disabled=false);});
$('[data-copy]').addEventListener('click',async()=>{if(!draft)return;await navigator.clipboard.writeText(draft);message.textContent='Borrador copiado en este dispositivo.';});
$('[data-download]').addEventListener('click',()=>{if(!draft)return;const url=URL.createObjectURL(new Blob([draft],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`FIA-${current.id}-borrador.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
$('[data-print]').addEventListener('click',()=>{if(draft)window.print();});
$('[data-clear]').addEventListener('click',()=>{form.reset();clearOutput();});
$('#model-search').addEventListener('input',e=>renderList(e.target.value));
window.addEventListener('pagehide',()=>{form.reset();draft='';});
renderList();select(new URLSearchParams(location.search).get('model')||MODELS[0].id);
})();