(function(global){'use strict';
const VERSION='0.1-demo';
const PROFILES={
  OPS_ASSISTANT:{label:'Operaciones / soporte',monthlyCost:900,hours:80,productivityPct:85},
  PART_TIME_SPECIALIST:{label:'Especialista part-time',monthlyCost:1300,hours:80,productivityPct:95},
  FULL_TIME_OPERATOR:{label:'Operaciones full-time',monthlyCost:2200,hours:160,productivityPct:100}
};
function n(v,d){v=Number(v);return Number.isFinite(v)?v:d;}
function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
function evaluate(capacity,profileKey,options){options=options||{};if(!capacity)throw new Error('Capacidad founder no disponible');const p=PROFILES[profileKey]||PROFILES.OPS_ASSISTANT;const revenuePerManagement=Math.max(0,n(options.revenuePerManagement,24));const contributionRate=clamp(n(options.contributionRatePct,60),0,100)/100;const customMonthlyCost=Math.max(0,n(options.monthlyCost,p.monthlyCost));const customHours=Math.max(1,n(options.monthlyHours,p.hours));const productivity=clamp(n(options.productivityPct,p.productivityPct),1,100)/100;const minutesPerManagement=Math.max(0.1,n(capacity.humanMinutesPerManagement,10));const effectiveMinutes=customHours*60*productivity;const addedCapacity=Math.floor(effectiveMinutes/minutesPerManagement);const contributionPerManagement=revenuePerManagement*contributionRate;const breakEvenAddedManagements=contributionPerManagement>0?Math.ceil(customMonthlyCost/contributionPerManagement):null;const expectedUtilization=clamp(n(options.expectedUtilizationPct,70),0,100)/100;const expectedAddedManagements=Math.floor(addedCapacity*expectedUtilization);const expectedIncrementalContribution=expectedAddedManagements*contributionPerManagement;const monthlyNetImpact=expectedIncrementalContribution-customMonthlyCost;const economicallyReady=breakEvenAddedManagements!==null&&expectedAddedManagements>=breakEvenAddedManagements&&capacity.hireSignal==='PREPARE_HIRE';return {version:VERSION,profile:profileKey,label:p.label,monthlyCost:customMonthlyCost,monthlyHours:customHours,productivityPct:Math.round(productivity*100),addedCapacity,expectedAddedManagements,contributionPerManagement:Math.round(contributionPerManagement*100)/100,breakEvenAddedManagements,expectedIncrementalContribution:Math.round(expectedIncrementalContribution*100)/100,monthlyNetImpact:Math.round(monthlyNetImpact*100)/100,economicallyReady,recommendation:economicallyReady?'CONSIDER_HIRE':'DELAY_HIRE',assumptionOnly:true,noHiringAction:true,noFinancialCommitment:true,persistentStorage:false,containsPersonalData:false};}
function compare(capacity,options){return Object.keys(PROFILES).map(k=>evaluate(capacity,k,options)).sort((a,b)=>b.monthlyNetImpact-a.monthlyNetImpact);}
global.FIACOHiringModel={version:VERSION,profiles:PROFILES,evaluate,compare};
})(typeof window!=='undefined'?window:globalThis);
