(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const stages=['create','agreement','documents','tracking','delivery','close'];
const labels={create:'CREADA',agreement:'ACUERDO CONFIRMADO',documents:'DOCUMENTACIÓN VALIDADA',tracking:'EN SEGUIMIENTO',delivery:'ENTREGADA',close:'CERRADA'};
const next={create:'Confirma el acuerdo',agreement:'Comprueba la documentación',documents:'Inicia el seguimiento',tracking:'Confirma la entrega',delivery:'Revisa y cierra la operación',close:'Operación finalizada'};
const required={agreement:['conditions','version','human'],documents:['model','authority','minimum'],tracking:['prepared'],delivery:['before','after','accepted'],close:['reviewed']};
let state={created:false,index:0,reference:'',incident:false,closed:false,events:[]};
const status=$('[data-status]'),reference=$('[data-reference]'),percent=$('[data-percent]'),message=$('[data-message]'),nextAction=$('[data-next]'),incidentBox=$('[data-incident]'),download=$('[data-download]');
function sensitive(value){const t=String(value||'');return /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i.test(t)||/\bES\d{22}\b/i.test(t.replace(/\s+/g,''))||/\b(?:\d{8}[A-Z]|[XYZ]\d{7}[A-Z])\b/i.test(t)||/\b(?:api[_ -]?key|token|secret|password|contrasena)\s*[:=]\s*\S{6,}/i.test(t);}
function log(text){state.events.unshift({at:new Date().toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'}),text});renderLog();}
function renderLog(){const host=$('[data-log]');host.replaceChildren();for(const event of state.events){const li=document.createElement('li'),time=document.createElement('time'),span=document.createElement('span');time.textContent=event.at;span.textContent=event.text;li.append(time,span);host.append(li);}}
function setMessage(text,type=''){message.textContent=text;message.className=type;}
function show(index){state.index=index;$$('[data-stage]').forEach((el,i)=>el.hidden=i!==index);$$('[data-step-indicator]').forEach((el,i)=>{el.classList.toggle('done',i<index||state.closed);el.classList.toggle('active',i===index&&!state.closed);});percent.textContent=`${state.closed?100:Math.round(index/(stages.length-1)*100)} %`;status.textContent=state.closed?'CERRADA':state.created?labels[stages[Math.max(0,index-1)]]||'CREADA':'PREPARACIÓN';nextAction.textContent=state.closed?next.close:state.created?next[stages[Math.max(0,index-1)]]:'Crea la operación ficticia';download.disabled=!state.closed;}
function checked(names){return names.every(name=>$(`[data-check="${name}"]`)?.checked);}
function advance(stage){if(state.incident){setMessage('La operación está congelada hasta resolver la incidencia.','error');return;}const index=stages.indexOf(stage);if(required[stage]&&!checked(required[stage])){setMessage('Completa todos los controles de esta fase antes de avanzar.','error');return;}if(stage==='tracking'){const value=$('[data-field="tracking"]').value.trim();if(!value){setMessage('Añade una referencia ficticia de entrega.','error');return;}if(sensitive(value)){setMessage('Referencia rechazada: parece contener información sensible.','error');return;}}if(stage==='close'&&!$('[data-field="payment"]').value){setMessage('Selecciona el estado comunicado por el proveedor.','error');return;}log(`${labels[stage]} · control humano registrado`);if(stage==='close'){state.closed=true;show(5);setMessage('Operación ficticia cerrada. Ya puedes descargar el resumen.','success');return;}show(index+1);setMessage('Fase completada. Puedes continuar con el siguiente control.','success');}
function create(){const values=$$('[data-stage="create"] input').map(x=>x.value.trim());if(values.some(x=>!x)){setMessage('Completa los campos de la operación ficticia.','error');return;}if(values.some(sensitive)){setMessage('Creación bloqueada: elimina datos personales, bancarios o credenciales.','error');return;}state.created=true;state.reference=`FIA-DEMO-${String(Date.now()).slice(-6)}`;reference.textContent=state.reference;log('Operación ficticia creada');show(1);setMessage('Operación creada sin enviar información fuera del dispositivo.','success');}
function incident(){if(!state.created||state.closed)return;state.incident=true;incidentBox.hidden=false;status.textContent='CONGELADA';nextAction.textContent='Resolver incidencia mediante revisión humana';log('Incidencia simulada: avance bloqueado');setMessage('Incidencia contenida. No se puede avanzar.','error');}
function resolve(){state.incident=false;incidentBox.hidden=true;log('Incidencia revisada y resuelta por una persona');show(state.index);setMessage('Incidencia recuperada. La operación puede continuar.','success');}
function reset(){state={created:false,index:0,reference:'',incident:false,closed:false,events:[]};$$('input[type="checkbox"]').forEach(x=>x.checked=false);$$('input:not([type="checkbox"])').forEach(x=>{if(x.dataset.field==='partyA')x.value='Empresa Demo A';else if(x.dataset.field==='partyB')x.value='Empresa Demo B';else if(x.dataset.field==='subject')x.value='Vehículo de demostración';else x.value='';});$$('select').forEach(x=>x.selectedIndex=0);reference.textContent='Sin crear';incidentBox.hidden=true;renderLog();log('Centro reiniciado; toda la operación anterior se ha eliminado');show(0);setMessage('Los campos contienen ejemplos y pueden modificarse sin usar datos reales.');}
function summary(){const lines=['FIA&CO · RESUMEN DE OPERACIÓN SINTÉTICA',`Referencia: ${state.reference}`,'Estado: CERRADA','Datos reales: NO','Fondos movidos por FIA&CO: NO','',...state.events.slice().reverse().map(x=>`${x.at} · ${x.text}`),'','Documento de demostración sin efectos jurídicos.'];const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`${state.reference}-resumen.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$$('[data-action]').forEach(button=>button.addEventListener('click',()=>{const action=button.dataset.action;if(action==='create')create();else if(action==='incident')incident();else if(action==='resolve')resolve();else advance(action);}));
$('[data-reset]').addEventListener('click',reset);download.addEventListener('click',summary);$('[data-field="type"]').addEventListener('change',event=>{const type=event.target.value;$('[data-model-link]').href=`form-models.html?model=${encodeURIComponent(type)}`;});
window.addEventListener('pagehide',()=>{state.events=[];});show(0);
})();
