(function(global){'use strict';
const VERSION='0.1-demo';
const ALLOWED=['CLASSIFY','PREPARE_CHECKLIST','DRAFT_REPLY','FOLLOW_UP','ESCALATE'];
const BLOCKED=['MOVE_FUNDS','APPROVE_PAYMENT','REFUND','CHANGE_IDENTITY','EXPORT_SENSITIVE_DATA','DELETE_RECORDS'];
function n(v,d){const x=Number(v);return Number.isFinite(x)?x:d;}
function policy(input){input=input||{};return {version:VERSION,mode:'LOCAL_MOCK_DEFAULT',externalProviderEnabled:input.externalProviderEnabled===true,maxRetries:Math.max(0,Math.min(2,Math.floor(n(input.maxRetries,1)))),maxActionsPerManagement:Math.max(1,Math.min(20,Math.floor(n(input.maxActionsPerManagement,8)))),maxEstimatedCostEurPerManagement:Math.max(0,Math.min(50,n(input.maxEstimatedCostEurPerManagement,0))),allowedActions:ALLOWED.slice(),blockedActions:BLOCKED.slice(),realCredentialsConfigured:false,productionExecutionEnabled:false};}
function authorize(request,p,state){request=request||{};p=p||policy();state=state||{};const action=String(request.action||'').toUpperCase(),provider=String(request.provider||'LOCAL_MOCK').toUpperCase(),estimatedCost=Math.max(0,n(request.estimatedCostEur,0)),retryCount=Math.max(0,Math.floor(n(request.retryCount,0))),actionsUsed=Math.max(0,Math.floor(n(state.actionsUsed,0))),costUsed=Math.max(0,n(state.estimatedCostUsedEur,0));let reason='ALLOWED_LOCAL_DEMO';let allowed=true,requiresHuman=false;if(BLOCKED.includes(action)||!ALLOWED.includes(action)){allowed=false;reason='ACTION_NOT_ALLOWED';requiresHuman=true;}else if(provider!=='LOCAL_MOCK'&&!p.externalProviderEnabled){allowed=false;reason='EXTERNAL_PROVIDER_DISABLED';}else if(retryCount>p.maxRetries){allowed=false;reason='RETRY_LIMIT_EXCEEDED';}else if(actionsUsed>=p.maxActionsPerManagement){allowed=false;reason='ACTION_LIMIT_EXCEEDED';}else if(costUsed+estimatedCost>p.maxEstimatedCostEurPerManagement){allowed=false;reason='BUDGET_LIMIT_EXCEEDED';}else if(request.riskFlag===true||request.promptInjection===true){allowed=false;reason='HUMAN_ESCALATION_REQUIRED';requiresHuman=true;}return {allowed,reason,requiresHuman,action,provider,retryCount,estimatedCostEur:estimatedCost,actionsUsed,costUsedEur:costUsed,remainingBudgetEur:Math.max(0,p.maxEstimatedCostEurPerManagement-costUsed),financialAuthority:false,externalSendAllowed:false,productionExecutionEnabled:false,persistentStorage:false,containsPersonalData:false};}
global.FIACOProviderGuard={version:VERSION,allowedActions:ALLOWED,blockedActions:BLOCKED,policy,authorize};
})(typeof window!=='undefined'?window:globalThis);
