(()=>{
'use strict';

const STORAGE_KEY='fia_unified_beta_v2';
const now=()=>new Date().toISOString();
const uid=(prefix)=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const safeNumber=(value)=>Number.isFinite(Number(value))?Number(value):0;
const money=(value)=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(safeNumber(value));
const dateLabel=(value)=>{if(!value)return 'Sin fecha';const d=new Date(value);return Number.isNaN(d.getTime())?String(value):new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(d)};
const el=(selector,root=document)=>root.querySelector(selector);
const els=(selector,root=document)=>[...root.querySelectorAll(selector)];

function emptyState(){
  return {version:2,selectedOperationId:null,operations:[],evidence:[],participants:[],ledger:[],activity:[]};
}

function load(){
  try{
    const raw=localStorage.getItem(STORAGE_KEY);
    if(!raw)return emptyState();
    const parsed=JSON.parse(raw);
    if(parsed&&parsed.version===2&&Array.isArray(parsed.operations)&&Array.isArray(parsed.evidence)&&Array.isArray(parsed.participants)&&Array.isArray(parsed.ledger)&&Array.isArray(parsed.activity))return parsed;
  }catch(_e){}
  return emptyState();
}

function save(next){
  try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));}catch(_e){}
  return next;
}

let state=load();

function activity(textValue){
  state.activity.unshift({id:uid('act'),text:String(textValue||'').slice(0,180),createdAt:now()});
  state.activity=state.activity.slice(0,30);
}
function getOp(id){return state.operations.find(op=>op.id===id)||null;}
function selectedOp(){return getOp(state.selectedOperationId)||state.operations[0]||null;}
function evidenceFor(id){return state.evidence.filter(item=>item.operationId===id);}
function needsLogistics(op){return Boolean(op)&&['sale_transport','transport','special','animal'].includes(op.type);}
function incidentFor(id){return evidenceFor(id).some(item=>item.type==='Incidencia');}
function deriveStatus(op){if(op.completed)return 'completed';if(incidentFor(op.id))return 'review';if(evidenceFor(op.id).length>0)return 'validation';return 'draft';}
function risk(op){
  if(!op)return {level:'medium',title:'Selecciona un expediente',recommendation:'SELECT_OPERATION',points:['No hay expediente seleccionado.']};
  const points=[];
  let score=0;
  if(!op.reference||!op.cargo){score+=2;points.push('Faltan datos mínimos del expediente.');}
  if(evidenceFor(op.id).length===0){score+=2;points.push('No hay evidencias vinculadas.');}
  if(incidentFor(op.id)){score+=3;points.push('Existe una incidencia registrada: requiere revisión humana.');}
  if(needsLogistics(op)&&!op.logistics){score+=2;points.push('La operación requiere coordinación logística y todavía no tiene plan.');}
  if(needsLogistics(op)&&op.logistics&&!op.logistics.milestones.delivered){score+=1;points.push('La entrega todavía no está marcada como completada.');}
  if(points.length===0)points.push('Los datos mínimos están completos; mantener revisión antes del cierre.');
  const level=score>=4?'high':score>=2?'medium':'low';
  const recommendation=level==='high'?'SUGGEST_REVIEW':level==='medium'?'COMPLETE_REQUIREMENTS':'READY_FOR_HUMAN_CONFIRMATION';
  const title=level==='high'?'Revisión recomendada':level==='medium'?'Completar requisitos':'Riesgo demo bajo';
  return {level,title,recommendation,points};
}
function text(tag,value,className){const node=document.createElement(tag);node.textContent=value;if(className)node.className=className;return node;}
function button(label,className,handler){const node=text('button',label,className);node.type='button';node.addEventListener('click',handler);return node;}
function ensureOperationTypes(){const select=el('[data-operation-form] select[name="type"]');if(select&&!select.querySelector('option[value="animal"]')){const option=document.createElement('option');option.value='animal';option.textContent='Transporte animal';select.append(option);}}
function showView(name){els('[data-view]').forEach(view=>{const active=view.dataset.view===name;view.hidden=!active;view.classList.toggle('active',active);});els('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.viewTarget===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='premium')renderPremium();if(name==='dashboard')renderDashboard();}
function bindNavigation(){els('[data-view-target]').forEach(node=>node.addEventListener('click',()=>showView(node.dataset.viewTarget)));}
function renderMetrics(){const active=state.operations.filter(op=>!op.completed).length;const alerts=state.operations.filter(op=>risk(op).level==='high').length;const values={operations:state.operations.length,active,evidence:state.evidence.length,alerts};Object.entries(values).forEach(([key,value])=>els(`[data-metric="${key}"]`).forEach(node=>node.textContent=String(value)));}
function opTypeLabel(type){return ({sale:'Compraventa',sale_transport:'Venta + transporte',transport:'Transporte / logística',conditional:'Condicionada',special:'Porte especial',animal:'Transporte animal'})[type]||type;}
function statusLabel(op){return ({draft:'Borrador',validation:'En validación',review:'En revisión',completed:'Completada'})[deriveStatus(op)]||'Borrador';}
function renderOperationCards(target,items,compact=false){if(!target)return;target.replaceChildren();if(items.length===0){target.append(text('p','Todavía no hay operaciones demo.','empty-state'));return;}items.forEach(op=>{const card=document.createElement('button');card.type='button';card.className='operation-card'+(op.id===state.selectedOperationId?' selected':'');const left=document.createElement('span');left.append(text('strong',op.reference||'Sin referencia'));left.append(text('small',`${opTypeLabel(op.type)} · ${op.cargo||'Sin objeto'}${compact?'':` · ${money(op.amount)}`}`));card.append(left,text('span',statusLabel(op),'state'));card.addEventListener('click',()=>{state.selectedOperationId=op.id;save(state);renderAll();if(!compact)renderOperationDetail();});target.append(card);});}
function renderOverview(){const recent=el('[data-recent-operations]');renderOperationCards(recent,state.operations.slice(0,4),true);const op=selectedOp(),r=risk(op),title=el('[data-next-title]'),copy=el('[data-next-copy]'),action=el('[data-next-action]');if(!title||!copy||!action)return;if(!op){title.textContent='Crea tu primer expediente';copy.textContent='Empieza con una operación demo vacía, sin datos precargados.';action.textContent='Crear operación';action.dataset.nextView='operations';}else if(needsLogistics(op)&&!op.logistics){title.textContent='Configura logística';copy.textContent=`${op.reference} necesita un plan de proveedor externo antes de continuar.`;action.textContent='Abrir logística';action.dataset.nextView='logistics';}else if(evidenceFor(op.id).length===0){title.textContent='Añade evidencia';copy.textContent=`${op.reference} todavía no tiene evidencias demo vinculadas.`;action.textContent='Abrir evidencias';action.dataset.nextView='evidence';}else if(r.level==='high'){title.textContent='Revisión recomendada';copy.textContent=`${op.reference} contiene señales que deben revisar personas responsables.`;action.textContent='Abrir Premium';action.dataset.nextView='premium';}else{title.textContent='Revisa el expediente';copy.textContent=`${op.reference} tiene los elementos demo mínimos para una revisión humana.`;action.textContent='Ver operación';action.dataset.nextView='operations';}}
function renderOperationList(){renderOperationCards(el('[data-operation-list]'),state.operations);const count=el('[data-operation-count]');if(count)count.textContent=String(state.operations.length);}
function renderOperationDetail(){const host=el('[data-operation-detail]');if(!host)return;host.replaceChildren();const op=selectedOp();if(!op){host.append(text('p','Selecciona una operación para ver su timeline y controles.','empty-state'));return;}const wrap=document.createElement('div');wrap.className='detail-grid';const left=document.createElement('div');const heading=document.createElement('div');heading.className='detail-title';const hgroup=document.createElement('div');hgroup.append(text('h2',op.reference));hgroup.append(text('div',`${opTypeLabel(op.type)} · ${money(op.amount)} · ${op.origin||'Origen pendiente'} → ${op.destination||'Destino pendiente'}`,'detail-meta'));heading.append(hgroup,text('span',statusLabel(op),'pill'));left.append(heading);const timeline=document.createElement('ol');timeline.className='timeline';const hasEvidence=evidenceFor(op.id).length>0,hasLog=!needsLogistics(op)||Boolean(op.logistics),reviewed=risk(op).level==='low';const steps=[['Creación',true,'Datos mínimos del expediente'],['Coordinación',hasLog,needsLogistics(op)?'Plan logístico externo':'No requerida'],['Evidencias',hasEvidence,`${evidenceFor(op.id).length} registro(s)`],['Revisión',reviewed,risk(op).recommendation],['Cierre simulado',op.completed,op.completed?'Completado':'Pendiente de confirmación humana']];steps.forEach(([name,done,desc],i)=>{const li=document.createElement('li');if(done)li.className='done';const content=document.createElement('span');content.append(text('strong',`${i+1} · ${name}`));content.append(text('small',desc));li.append(content);timeline.append(li);});left.append(timeline);const right=document.createElement('div');right.className='detail-actions';right.append(text('p',op.condition||'Sin condición principal registrada.','safe-note'));if(needsLogistics(op))right.append(button(op.logistics?'Editar logística':'Configurar logística','secondary-button',()=>showView('logistics')));right.append(button('Añadir evidencia','secondary-button',()=>showView('evidence')));right.append(button('Analizar con Premium','secondary-button',()=>showView('premium')));if(!op.completed)right.append(button('Cerrar operación en demo','primary-button',()=>{op.completed=true;activity(`Operación ${op.reference} cerrada en modo demo`);save(state);renderAll();renderOperationDetail();}));wrap.append(left,right);host.append(wrap);}
function syncOperationSelects(){els('[data-operation-select]').forEach(select=>{const current=select.value||state.selectedOperationId;select.replaceChildren();if(state.operations.length===0){const option=document.createElement('option');option.value='';option.textContent='Primero crea una operación';select.append(option);return;}state.operations.forEach(op=>{const option=document.createElement('option');option.value=op.id;option.textContent=`${op.reference} · ${opTypeLabel(op.type)}`;select.append(option);});select.value=getOp(current)?current:(state.selectedOperationId||state.operations[0].id);});}
function renderLogistics(){const select=el('[data-logistics-form] [data-operation-select]');if(select&&state.selectedOperationId)select.value=state.selectedOperationId;const id=select?select.value:state.selectedOperationId,op=getOp(id),host=el('[data-logistics-summary]');if(!host)return;host.replaceChildren();if(!op||!op.logistics){host.append(text('p','Selecciona una operación con plan logístico.','empty-state'));return;}const log=op.logistics,card=document.createElement('div');card.className='summary-card';card.append(text('strong',log.provider||'Proveedor demo sin nombre'));card.append(text('small',`Recogida: ${log.pickup||'pendiente'} · Entrega: ${log.delivery||'pendiente'}`));card.append(text('small',log.requirements||'Sin requisitos adicionales'));host.append(card);const grid=document.createElement('div');grid.className='milestone-grid';[['assigned','Asignado'],['picked','Recogido'],['delivered','Entregado']].forEach(([key,label])=>{const m=document.createElement('button');m.type='button';m.className='milestone'+(log.milestones[key]?' done':'');m.append(text('strong',label));m.append(text('small',log.milestones[key]?'Completado':'Marcar demo'));m.addEventListener('click',()=>{log.milestones[key]=!log.milestones[key];activity(`${op.reference}: hito ${label.toLowerCase()} ${log.milestones[key]?'completado':'reabierto'}`);save(state);renderAll();renderLogistics();});grid.append(m);});host.append(grid);}
function renderEvidence(){const host=el('[data-evidence-list]');if(!host)return;host.replaceChildren();const count=el('[data-evidence-count]');if(count)count.textContent=String(state.evidence.length);if(state.evidence.length===0){host.append(text('p','No hay evidencias demo.','empty-state'));return;}state.evidence.slice().reverse().forEach(item=>{const op=getOp(item.operationId),row=document.createElement('div');row.className='evidence-item';row.append(text('strong',`${item.type} · ${item.reference}`));row.append(text('small',`${op?op.reference:'Operación eliminada'} · ${item.note||'Sin nota'} · ${dateLabel(item.createdAt)}`));host.append(row);});}
function renderParticipants(){const host=el('[data-participant-list]');if(!host)return;host.replaceChildren();const count=el('[data-participant-count]');if(count)count.textContent=String(state.participants.length);if(state.participants.length===0){host.append(text('p','No hay participantes demo.','empty-state'));return;}state.participants.forEach(item=>{const row=document.createElement('div');row.className='participant-item';row.append(text('strong',item.name));row.append(text('small',`${item.role} · ${item.scope} · identidad ficticia`));host.append(row);});}
function renderWallet(){const reserved=state.ledger.filter(x=>x.action==='reserve').reduce((sum,x)=>sum+x.amount,0)-state.ledger.filter(x=>x.action==='release'||x.action==='refund').reduce((sum,x)=>sum+x.amount,0),total=state.operations.reduce((sum,op)=>sum+safeNumber(op.amount),0);const balance=el('[data-wallet-balance]'),reservedNode=el('[data-wallet-reserved]'),reconciled=el('[data-wallet-reconciled]');if(balance)balance.textContent=money(Math.max(total-reserved,0));if(reservedNode)reservedNode.textContent=money(Math.max(reserved,0));if(reconciled)reconciled.textContent=String(state.ledger.length);const host=el('[data-wallet-ledger]');if(!host)return;host.replaceChildren();if(state.ledger.length===0){host.append(text('p','Todavía no hay movimientos simulados.','empty-state'));return;}state.ledger.slice().reverse().forEach(item=>{const op=getOp(item.operationId),row=document.createElement('div');row.className='ledger-item';row.append(text('strong',`${({reserve:'Reserva',release:'Liberación',refund:'Devolución'})[item.action]||item.action} · ${money(item.amount)}`));row.append(text('small',`${op?op.reference:'Operación'} · SIMULADO · ${dateLabel(item.createdAt)}`));host.append(row);});}
function renderPremium(){const select=el('[data-premium-operation]');if(select&&state.selectedOperationId)select.value=state.selectedOperationId;const host=el('[data-premium-result]');if(!host)return;const op=getOp(select?select.value:state.selectedOperationId);host.replaceChildren();if(!op){host.append(text('p','Selecciona una operación y genera un análisis.','empty-state'));return;}host.append(text('p',`Preparado para analizar ${op.reference}. Pulsa “Generar análisis”.`,'empty-state'));}
function runPremium(){const select=el('[data-premium-operation]'),op=getOp(select?select.value:state.selectedOperationId),r=risk(op),host=el('[data-premium-result]');if(!host)return;host.replaceChildren();const box=document.createElement('div');box.className=`risk-box ${r.level}`;box.append(text('h3',`${r.title} · ${r.recommendation}`));box.append(text('p',op?`Análisis local del expediente ${op.reference}. No modifica el estado.`:'Sin expediente.'));const ul=document.createElement('ul');ul.className='risk-points';r.points.forEach(point=>ul.append(text('li',point)));box.append(ul);host.append(box);if(op){activity(`Premium analizó ${op.reference}: ${r.recommendation}`);save(state);renderDashboard();}}
function renderDashboard(){const counts={drafts:0,validation:0,logistics:0,completed:0};state.operations.forEach(op=>{const s=deriveStatus(op);if(s==='draft')counts.drafts++;if(s==='validation'||s==='review')counts.validation++;if(op.logistics)counts.logistics++;if(op.completed)counts.completed++;});Object.entries(counts).forEach(([key,value])=>{const node=el(`[data-dashboard="${key}"]`);if(node)node.textContent=String(value);});const table=el('[data-dashboard-operations]');if(table){table.replaceChildren();const header=document.createElement('div');header.className='dashboard-row header';['Expediente','Estado','Evidencias','Riesgo'].forEach(v=>header.append(text('span',v)));table.append(header);state.operations.forEach(op=>{const row=document.createElement('div');row.className='dashboard-row';row.append(text('strong',op.reference));row.append(text('span',statusLabel(op)));row.append(text('span',String(evidenceFor(op.id).length)));row.append(text('span',risk(op).level.toUpperCase()));table.append(row);});}const acts=el('[data-activity-list]');if(acts){acts.replaceChildren();if(state.activity.length===0)acts.append(text('p','Sin actividad todavía.','empty-state'));state.activity.slice(0,8).forEach(item=>{const row=document.createElement('div');row.className='activity-item';row.append(text('strong',item.text));row.append(text('small',dateLabel(item.createdAt)));acts.append(row);});}}
function renderAll(){renderMetrics();renderOverview();renderOperationList();syncOperationSelects();renderOperationDetail();renderLogistics();renderEvidence();renderParticipants();renderWallet();renderDashboard();}
function bindForms(){
  const operationForm=el('[data-operation-form]');if(operationForm)operationForm.addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),reference=String(data.get('reference')||'').trim(),cargo=String(data.get('cargo')||'').trim();if(!reference||!cargo)return;const op={id:uid('op'),type:String(data.get('type')||'sale'),reference,amount:safeNumber(data.get('amount')),cargo,origin:String(data.get('origin')||'').trim(),destination:String(data.get('destination')||'').trim(),condition:String(data.get('condition')||'').trim(),createdAt:now(),completed:false,logistics:null};state.operations.unshift(op);state.selectedOperationId=op.id;activity(`Operación ${op.reference} creada`);save(state);form.reset();const status=el('[data-operation-status]');if(status)status.textContent='Expediente demo guardado.';renderAll();});
  const logisticsForm=el('[data-logistics-form]');if(logisticsForm)logisticsForm.addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),op=getOp(String(data.get('operationId')||''));if(!op)return;op.logistics={provider:String(data.get('provider')||'Proveedor demo pendiente').trim(),pickup:String(data.get('pickup')||''),delivery:String(data.get('delivery')||''),requirements:String(data.get('requirements')||'').trim(),milestones:op.logistics?.milestones||{assigned:true,picked:false,delivered:false}};op.logistics.milestones.assigned=true;state.selectedOperationId=op.id;activity(`${op.reference}: plan logístico actualizado`);save(state);const status=el('[data-logistics-status]');if(status)status.textContent='Plan logístico demo guardado.';renderAll();});
  const evidenceForm=el('[data-evidence-form]');if(evidenceForm)evidenceForm.addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),op=getOp(String(data.get('operationId')||''));if(!op)return;const reference=String(data.get('reference')||'').trim();if(!reference)return;const item={id:uid('ev'),operationId:op.id,type:String(data.get('type')||'Documento'),reference,note:String(data.get('note')||'').trim(),createdAt:now()};state.evidence.push(item);state.selectedOperationId=op.id;activity(`${op.reference}: evidencia ${item.reference} vinculada`);save(state);form.reset();const status=el('[data-evidence-status]');if(status)status.textContent='Evidencia demo vinculada.';renderAll();});
  const participantForm=el('[data-participant-form]');if(participantForm)participantForm.addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),name=String(data.get('name')||'').trim();if(!name)return;const item={id:uid('p'),name,role:String(data.get('role')||''),scope:String(data.get('scope')||'')};state.participants.push(item);activity(`Participante demo añadido: ${item.name}`);save(state);form.reset();const status=el('[data-participant-status]');if(status)status.textContent='Participante demo añadido.';renderAll();});
  const walletForm=el('[data-wallet-form]');if(walletForm)walletForm.addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),op=getOp(String(data.get('operationId')||''));if(!op)return;const action=String(data.get('action')||'reserve'),amount=safeNumber(op.amount);state.ledger.push({id:uid('led'),operationId:op.id,action,amount,createdAt:now()});activity(`${op.reference}: movimiento económico demo ${action}`);save(state);const status=el('[data-wallet-status]');if(status)status.textContent='Movimiento simulado registrado. No se ha movido dinero real.';renderAll();});
}
function bindControls(){const next=el('[data-next-action]');if(next)next.addEventListener('click',event=>showView(event.currentTarget.dataset.nextView||'operations'));els('[data-logistics-form] [data-operation-select]').forEach(node=>node.addEventListener('change',()=>{state.selectedOperationId=node.value;save(state);renderLogistics();}));const premium=el('[data-premium-operation]');if(premium)premium.addEventListener('change',event=>{state.selectedOperationId=event.currentTarget.value;save(state);renderPremium();});const run=el('[data-run-premium]');if(run)run.addEventListener('click',runPremium);const reset=el('[data-reset-demo]');if(reset)reset.addEventListener('click',()=>{state=emptyState();save(state);renderAll();showView('overview');});const exportButton=el('[data-export-demo]');if(exportButton)exportButton.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download='fia-co-demo-state.json';document.body.append(a);a.click();a.remove();URL.revokeObjectURL(href);});}

ensureOperationTypes();
bindNavigation();
bindForms();
bindControls();
renderAll();
})();
